### ISSUE TITLE
Sugestão de pacotes 

### ISSUE THREAD

**Issue by eminetto** [Diego-Brocanelli/workstation_configuration#6]
Sugiro instalar também o docker e o docker-compose

**Comment by Diego-Brocanelli** [comment]
Obrigado pela sugestão.

Está em processo de implementação 😃

**Comment by Diego-Brocanelli** [comment]
Finalizado processo de implementação da issue.  Disponível na versão [4.0.0](https://github.com/Diego-Brocanelli/workstation_configuration/releases/tag/4.0.0).

Obrigado pela sugestão de melhoria para a ferramenta.
