### ISSUE TITLE
Sugestão de mudança no setup

### ISSUE THREAD

**Issue by eminetto** [Diego-Brocanelli/workstation_configuration#7]
Uma sugestão: renomear o setup.sh para algo como setup.sh.example e colocar o setup.sh no .gitignore
Assim a pessoa teria que copiar o setup.sh.example para setup.sh antes de rodar o install. Desta forma evitaria conflitos caso o projeto altere o setup.sh e a pessoa fez alterações na máquina local

**Comment by Diego-Brocanelli** [comment]
Obrigado pela sugestão!

Está em processo de implementação 😃

**Comment by Diego-Brocanelli** [comment]
Finalizado processo de implementação da issue.  Disponível na versão [4.0.0](https://github.com/Diego-Brocanelli/workstation_configuration/releases/tag/4.0.0).

Obrigado pela sugestão de melhoria para a ferramenta.
